# Generated by Django 4.1 on 2022-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
